x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build:
      context: https://github.com/MydriveBot/Demo-vercel
      dockerfile: Dockerfile
   
    deploy:
      resources:
        limits:
          memory: 500M
