x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .

    environment: 
      NODE_ENV: staging

    restart: always 
    
    ports:
      - "8080:8080"
    privileged: true
    depends_on:
      - app
  
   
    deploy:
      resources:
        limits:
          memory: 500M
          
