x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    environment:
      NODE_ENV: staging
    deploy:
      resources:
        limits:
          memory: 4000M
    continuous_preview:
      deploy_preview_when_pull_request_is_opened: true
      delete_preview_when_pull_request_is_closed: true
      share_to_github: true      
    restart: always
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
