x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build:
      context: https://github.com/example/app
      dockerfile: Dockerfile
   
    deploy:
      resources:
        limits:
          memory: 500M
