x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build:
      context: https://github.com/MydriveBot/Demo-vercel
      dockerfile: Dockerfile
    mysevice:
      env_file: ./config.env  
    restart: always 
    ports:
      - "8080:8080"
    privileged: true
    depends_on:
      - app
  
   
    deploy:
      resources:
        limits:
          memory: 500M
          
